### ISSUE TITLE
Virtual Products

### ISSUE THREAD

**Issue by gerbesf** [intelipost/magento2-quote#10]
Quando um produto tem opções, e as mesmas são produtos virtuais, não está calculando o frete na página do produto.

Exemplo
![image](https://user-images.githubusercontent.com/12032611/52341409-9b438600-29f9-11e9-8745-db47c33ee300.png)

Convertendo os produtos para simples funciona normalmente.
update catalog_product_entity set type_id = 'simple' where type_id = 'virtual';

**Comment by marcoaacoliveira** [comment]
@gerbesf Esse comportamento dos produtos virtuais são o comportamento padrão do Magento, o produto virtual ele realmente não é entregue.
