### ISSUE TITLE
Ao dar o di:compile, da o erro :"Warning: "continue" targeting switch is equivalent to "break"."

### ISSUE THREAD

**Issue by marcelo011982** [intelipost/magento2-quote#13]
Apos colocar: bin/magento setup:di:compile logo ao instalar
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 79.0 MiB
In ErrorHandler.php line 61:
                                                                                                                                                                                  
  Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/vendor/intelipost/magento2-quote/Helper/Data.php on line 453

Provavel erro de compatibilidade na versao 7.3 do php

**Comment by luancschmitz** [comment]
estou enfrentando o mesmo problema. Pelo que verifiquei para corrigir isso, preicsa trocar o continue pelo break.

**Comment by marciomaciel** [comment]
Mesma situação por aqui, mas no meu caso o problema está ocorrendo na página de detalhes do produto. Erro intermitente.
- PHP 7.3

**Comment by marcoaacoliveira** [comment]
@marcelo011982 @luancschmitz @marciomaciel fechando issue por ter sido resolvida em [68a096ad170b877f9c1341648eb6df648c5f71dc](https://github.com/intelipost/magento2-quote/commit/68a096ad170b877f9c1341648eb6df648c5f71dc). Caso enfrentem algum outro problema correspondendo à versão 7.3 por favor abrir uma nova issue.
